sudo: required
services:
  - docker


before_install:
  - docker build -t nuclearfanta/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nuclearfanta/react-test npm test -- --coverage

after_success:
  - docker build -t nuclearfanta/multi-client ./client
  - docker build -t nuclearfanta/multi-nginx ./nginx
  - docker build -t nuclearfanta/multi-worker ./worker
  - docker build -t nuclearfanta/multi-server ./server  


  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nuclearfanta/multi-client
  - docker push nuclearfanta/multi-nginx
  - docker push nuclearfanta/multi-worker
  - docker push nuclearfanta/multi-server
